---
repos:
  - repo: https://github.com/tox-dev/tox-ini-fmt
    rev: 0.5.2
    hooks:
      - id: tox-ini-fmt
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.990
    hooks:
      - id: mypy
  - repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
      - id: black
