inherit_from: .rubocop_todo.yml

require:
  - rubocop-performance
  - rubocop-rails

AllCops:
  TargetRubyVersion: 2.4
  TargetRailsVersion: 4.2

Rails:
  Enabled: true

Style/AsciiComments:
  Enabled: false

Style/FormatString:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/PerlBackrefs:
  Enabled: false

Metrics/ModuleLength:
  Max: 200
