language: ruby
cache: bundler
rvm:
  - 2.4
  - 2.5

gemfiles:
  - Gemfile

branches:
  only:
    - master

addons:
  mariadb: '10.2'

before_script:
  - cp config/database.yml.mysql config/database.yml
  - mysql -e 'CREATE DATABASE glsamaker_test;'

script:
  - bundle exec rubocop
  - bundle exec rake test RAILS_ENV=test
