language: ruby
cache: bundler
rvm:
  - 2.4
  - 2.5

gemfiles:
  - Gemfile

branches:
  only:
    - master

addons:
  mariadb: '10.2'

before_install:
  - gem uninstall -v '>= 2' -i $(rvm gemdir)@global -ax bundler || true
  - gem install bundler -v '< 2'


before_script:
  - sed 's/i_forgot_to_set_this/"test-secret"/' < config/initializers/glsamaker.rb.sample > config/initializers/glsamaker.rb
  - cp config/database.yml.mysql config/database.yml
  - mysql -e 'CREATE DATABASE glsamaker_test;'

script:
  - bundle exec rubocop
  - bundle exec rake test RAILS_ENV=test
