version: '3.8'

services:
  http:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./etc:/etc/glsamaker
    ports:
      - "127.0.0.1:8080:8080"
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres:13
    volumes:
      - data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${GLSAMAKER_POSTGRES_USER:-root}
      POSTGRES_PASSWORD: ${GLSAMAKER_POSTGRES_PASS:-root}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 5s
volumes:
  data:
