---
version: '3.8'

services:
  http:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./etc:/etc/glsamaker
      - ./glsa:/var/lib/glsamaker/glsa
    ports:
      - "127.0.0.1:8080:8080"
    # debian bullseye (at least) has a very high open file limit which
    # triggers a possible bug in snakeoil in which it tries to close
    # all *possible* file descriptors rather than some subset of open
    # files..
    ulimits:
      nofile:
        soft: 1024
        hard: 1024
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres:13
    volumes:
      - data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 5s

volumes:
  data:
