version: '3.8'

services:
  http:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./etc:/etc/glsamaker
      - ./glsa:/var/lib/glsamaker/glsa
    ports:
      - 8080:8080
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres:13
    volumes:
      - data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 5s

volumes:
  data:
