version: '3.7'

services:
  http-serving:
    image: ${GLSAMAKER_IMAGE:-gentoo/glsamaker:latest}
    volumes:
      - type: "bind"
        source: "/var/log/glsamaker"
        target: "/var/log/glsamaker"
    ports:
      - 127.0.0.1:${GLSAMAKER_PORT:-5000}:5000
    labels:
      com.centurylinklabs.watchtower.enable: "true"
    restart: always
    environment:
      GLSAMAKER_LOG_FILE: '/var/log/glsamaker/web.log'
    command: "/go/src/glsamaker/bin/glsamaker --serve"
    depends_on:
      - db
  updater:
    image: ${GLSAMAKER_IMAGE:-gentoo/glsamaker:latest}
    volumes:
      - type: "bind"
        source: "/var/log/glsamaker"
        target: "/var/log/glsamaker"
    labels:
      com.centurylinklabs.watchtower.enable: "true"
    environment:
      GLSAMAKER_LOG_FILE: '/var/log/glsamaker/updater.log'
    command: "/go/src/glsamaker/bin/glsamaker --full-update"
    depends_on:
      - db
  db:
    image: postgres:12
    restart: always
    environment:
      POSTGRES_USER: ${GLSAMAKER_POSTGRES_USER:-root}
      POSTGRES_PASSWORD: ${GLSAMAKER_POSTGRES_PASSWORD:-root}
      POSTGRES_DB: ${GLSAMAKER_POSTGRES_DB:-glsamaker}
    volumes:
      - ${GLSAMAKER_POSTGRES_DATA_PATH:-/var/lib/postgresql/data}:/var/lib/postgresql/data
  watchtower:
    image: containrrr/watchtower:0.3.10
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /root/.docker/config.json:/config.json
    command: --label-enable
