version: '3.8'

services:
  http:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 127.0.0.1:8080:8080
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:13
    volumes:
      - /var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 5s
