version: '3.8'

services:
  http:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 127.0.0.1:8080:8080
    depends_on:
      - db
  db:
    image: postgres:13
    volumes:
      - /var/lib/postgresql/data
