#!/usr/bin/env ruby
PWD = File.dirname(__FILE__)

begin
  require 'yaml'

  puts "Initializing GLSAMaker 2 configuration in '#{File.expand_path(PWD + '/../')}'..."

  File.umask 0077

  puts "Reading configuration..."
  require PWD + '/../tmp/deploy.private.rb'

  Dir.chdir(File.join(PWD, '../config')) do
    puts "Setting database.yml..."
    y = YAML.load(open('database.yml.mysql'))

    if DB_CONN == :tcp
      y['production']['host'] = DB_HOST
      y['production']['port'] = DB_PORT
    elsif DB_CONN == :sock
      y['production']['socket'] = DB_SOCK
    end

    y['production']['username'] = DB_USER
    y['production']['password'] = DB_PASS
    y['production']['database'] = DB_DB

    File.open('database.yml', 'w') {|f| YAML.dump(y, f) }

    puts "Creating initializers/glsamaker.rb..."
    File.open('initializers/glsamaker.rb', 'w') do |f|
      f.write INITIALIZER
    end
  end

  puts "Removing deploy configuration"
  File.unlink(PWD + '/../tmp/deploy.private.rb')

  puts 'all done!'
rescue Exception => e
  $stderr.puts "!! Failed: #{e.message}"
  exit 1
end
