#!/bin/bash
# This populates the cache for GLSAMaker to fetch data about packages, and is only meant for running on production.
DESTDIR=/var/cache/glsamaker-portage/
SYNC='rsync://rsync.gentoo.org/gentoo-portage'
RSYNC='/usr/bin/rsync'
OPTIONS="-aq --delete-after"
OPTIONS+=" --include=*/*/metadata.xml"
OPTIONS+=" --include=metadata/*/* --include=metadata/*/*/*"
OPTIONS+=" --exclude=licenses/ --exclude=eclass/ --exclude=packages/"
OPTIONS+=" --exclude=skel.* --exclude=distfiles/ --exclude=profiles/"
OPTIONS+=" --exclude=header.txt"
OPTIONS+=" --exclude=*/*/*"

"${RSYNC}" ${OPTIONS} "${SYNC}" "${DESTDIR}"
